insert into cozinha (nome) values ('Tailandesa');
insert into cozinha (nome) values ('Indiana');
insert into restaurante (nome, taxa_frete, cozinha_id) values ('RestauranteDaFazenda', 10.7, 2);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('BomPrato',2.5,2);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('Thai Gourmet', 10,1);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('Thai Delivery', 9.50,1);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('Douglas Gourmet', 0,1);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('Flavia Delivery', 0,2);
insert into estado (nome) values ('SAO PAULO');
insert into estado (nome) values ('RIO GRANDE DO SUL');
insert into estado (nome) values ('CEARA');
insert into cidade (nome, estado_id) values ('JUNDIAI',1);
insert into cidade (nome, estado_id) values ('CAMPO LIMPO PAULISTA',1);
insert into cidade (nome, estado_id) values ('FORTALIZA',3);
insert into forma_pagamento (descricao) values ('Cartão de crédito');
insert into forma_pagamento (descricao) values ('Cartão de débito');
insert into forma_pagamento (descricao) values ('Dinheiro');
insert into permissao (id, nome, descricao) values (1, 'CONSULTAR_COZINHAS', 'Permite consultar cozinhas');
insert into permissao (id, nome, descricao) values (2, 'EDITAR_COZINHAS', 'Permite editar cozinhas');
insert into restaurante_forma_pagamento (restaurante_id, forma_pagamento_id) values (1, 1), (1, 2), (1, 3), (2, 3), (3, 2), (3, 3);