insert into cozinha (nome) values ('Tailandesa');
insert into cozinha (nome) values ('Indiana');
insert into restaurante (nome, taxa_frete, cozinha_id) values ('RestauranteDaFazenda', 10.7, 2);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('BomPrato',2.5,2);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('Thai Gourmet', 10,1);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('Thai Delivery', 9.50,1);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('Douglas Gourmet', 0,1);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('Flavia Delivery', 0,2);
insert into estado (nome) values ('SAO PAULO');
insert into estado (nome) values ('RIO GRANDE DO SUL');
insert into estado (nome) values ('CEARA');
insert into cidade (nome, estado_id) values ('JUNDIAI',1);
insert into cidade (nome, estado_id) values ('CAMPO LIMPO PAULISTA',1);
insert into cidade (nome, estado_id) values ('FORTALIZA',3);